name: build_image
on: push

jobs:
  build_passwall:
    name: Build Passwall
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:x86_64-master
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Print Pwd
      run: |
        chown -R build:build /__w/openwrt_workflow/openwrt_workflow/
        sudo -u build cp -r /__w/openwrt_workflow/openwrt_workflow/openwrt-passwall-3aff3af88536227d12fb7206992af64ff21cf4d2 /home/build/openwrt 
        cd /home/build/openwrt && pwd && ls 
        pwd
  