name: build_image
on: push

jobs:
  build_passwall:
    name: Build Passwall
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:x86_64-master
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Run Make
      run: |
        cp -r /__w/openwrt_workflow/openwrt_workflow /home/build/openwrt_workflow 
        chown -R build:build /home/build/openwrt_workflow 
        cd /home/build/openwrt 

        sudo -u build chmod +x /home/build/openwrt_workflow/build.sh 
        sudo -u build /home/build/openwrt_workflow/build.sh 
        cp bin/packages/x86_64/passwall.tar.gz /__w/openwrt_workflow/openwrt_workflow/
    - uses: actions/upload-artifact@v3
      with:
        name: passwall
        path: passwall.tar.gz 

  build_theme_argon:
    name: Build Argon 
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:x86_64-master
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Run Make
      run: |
        export VOLUME_HOME=$(pwd)
        cd /home/build/openwrt 
        sudo -u build git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
        sudo -u build ./scripts/feeds update -a
        sudo -u build make defconfig
        sudo -u build make package/luci-theme-argon/compile V=s -j1
        tar zcvf $VOLUME_HOME/luci-theme-argon.tar.gz bin/packages/x86_64/base/luci-theme-argon_2.2.9.4_all.ipk
    - uses: actions/upload-artifact@v3
      with:
        name: luci-theme-argon
        path: luci-theme-argon.tar.gz 
  
  # luci app netdata has some bugs, so just not use it for now!
  build_luci_app_netdata:
    name: Build Luci App Netdata 
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:x86_64-master
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Run Make
      run: |
        export VOLUME_HOME=$(pwd)
        cd /home/build/openwrt 
        sudo -u build git clone https://github.com/sirpdboy/luci-app-netdata package/luci-app-netdata
        sudo -u build ./scripts/feeds update -a
        sudo -u build ./scripts/feeds install -a
        sudo -u build make defconfig
        sudo -u build make package/luci-app-netdata/compile V=s -j1
        ls -alh bin/packages/x86_64/base/
        tar zcvf $VOLUME_HOME/luci-app-netdata.tar.gz bin/packages/x86_64/base/luci-app-netdata*.ipk
    - uses: actions/upload-artifact@v3
      with:
        name: luci-app-netdata
        path: luci-app-netdata.tar.gz 

  build_image:
    name: Build Image
    needs: [build_passwall, build_theme_argon, build_luci_app_netdata]
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/imagebuilder:x86-64-master
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: passwall
    - uses: actions/download-artifact@v3
      with:
        name: luci-theme-argon
    - uses: actions/download-artifact@v3
      with:
        name: luci-app-netdata
    - name: Prepare Passwall
      run: |
        export VOLUME_HOME=$(pwd)
        cd /home/build/openwrt
        mv $VOLUME_HOME/passwall.tar.gz packages
        pushd packages
        tar zxvf passwall.tar.gz
        rm passwall.tar.gz
        popd
    - name: Prepare Argon
      run: |
        export VOLUME_HOME=$(pwd)
        cd /home/build/openwrt
        mv $VOLUME_HOME/luci-theme-argon.tar.gz packages
        pushd packages
        tar zxvf luci-theme-argon.tar.gz
        rm luci-theme-argon.tar.gz
        popd
    - name: Prepare Netdata
      run: |
        export VOLUME_HOME=$(pwd)
        cd /home/build/openwrt
        mv $VOLUME_HOME/luci-app-netdata.tar.gz packages
        pushd packages
        tar zxvf luci-app-netdata.tar.gz
        rm luci-app-netdata.tar.gz
        popd
    - name: Debug Print
      run: |
        ls -alh /home/build/openwrt/packages
    - name: Make Image
      run: |
        export VOLUME_HOME=$(pwd)
        cd /home/build/openwrt
        chown -R build:build packages
        sudo -u build sed -i "s/CONFIG_TARGET_ROOTFS_PARTSIZE=[0-9]\+/CONFIG_TARGET_ROOTFS_PARTSIZE=1024/g;s/CONFIG_TARGET_KERNEL_PARTSIZE=[0-9]\+/CONFIG_TARGET_KERNEL_PARTSIZE=256/g" .config
        sudo -u build make image PROFILE=generic PACKAGES="luci luci-app-qos luci-app-upnp luci-proto-ipv6 kmod-igc luci-i18n-base-zh-cn netdata luci-app-passwall luci-theme-argon samba4-server luci-app-samba4 luci-app-ttyd ntpclient luci-app-ntpc -dnsmasq"
        cd bin/targets/x86/64/ 
        tar zcvf $VOLUME_HOME/openwrt-x86-64-master.tar.gz *
    - uses: actions/upload-artifact@v3
      with:
          name: openwrt
          path: openwrt-x86-64-master.tar.gz
