name: build_image
on: push

jobs:
  build_passwall:
    name: Build Passwall
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:x86_64-master
      options: --user build
    steps:
    - uses: actions/checkout@v2
    - name: Print Pwd
      run: |
        uname -a; pwd; ls -alh
  