name: build_image
on: push

jobs:
  build_passwall:
    name: Build Passwall
    runs-on: ubuntu-latest
    container: 
      image: openwrtorg/sdk:x86_64-master
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - name: Print Pwd
      run: |
        cp -r /__w/openwrt_workflow/openwrt_workflow /home/build/openwrt_workflow 
        chown -R build:build /home/build/openwrt_workflow 
        cd /home/build/openwrt 

        nproc
        sudo -u build chmod +x /home/build/openwrt_workflow/build.sh 
        sudo -u build /home/build/openwrt_workflow/build.sh 



  